#!/bin/bash
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --partition=v100
#SBATCH --output=%j.out
#SBATCH --error=%j.err


ulimit -s unlimited
ulimit -l unlimited

module load cuda/12.4
source /data/app/anaconda3/2024.10-1/etc/profile.d/conda.sh
conda activate hotham
export OMP_NUM_THREADS=1
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
MASTER_PORT=$((10000 + RANDOM % 50000))
torchrun --nproc_per_node=1 --master_port=$MASTER_PORT -m hotham.entrypoints.main inference.json > log
