#!/bin/sh
#SBATCH -N 1
#SBATCH --partition=p1
#SBATCH -n 40
#SBATCH --ntasks-per-node=40
#SBATCH --output=%j.out
#SBATCH --error=%j.err

export I_MPI_ADJUST_REDUCE=3
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENMX2HOTHAM=../../../0-dataset/1-openmx/script/openmx2hotham

ulimit -c 0

module purge
module load openmx/3.9-patch3.9.9-intel2023.2

COMPUTE_START() {
    touch computing
}

COMPUTE_END() {
    rm computing
}

CLEAN() {
    rm -rf *.cube
    rm -rf openmx_rst
    rm -rf openmx.scfout
}

IS_SUCCESSFUL0() {
    if test $? -ne 0
    then
        touch failed
        exit 1
    fi
}

IS_SUCCESSFUL1() {
    if test $? -ne 0
    then
        touch failed
	exit 1
    else
        touch finished
    fi
}

if ([ ! -f finished ] && [ ! -f unfinished ] && [ ! -f computing ] && [ ! -f failed ])
then
    COMPUTE_START
    mpirun -np 40 openmx openmx.dat > log
    IS_SUCCESSFUL0
    # select at least one from 'ham'(hamilton), 'olp'(overlap), and 'rr'(position matrix)
    mpirun -np 1 $OPENMX2HOTHAM openmx.scfout olp rr > Hks.txt
    IS_SUCCESSFUL1
    CLEAN    
    COMPUTE_END
fi

